We are finally learning how to handle exceptions yay